export const CountriesList = [
  { name: 'Argentina', code: 'ar' },
  { name: 'Australia', code: 'au' },
  { name: 'Austria', code: 'at' },
  { name: 'Belgium', code: 'be' },
  { name: 'Brazil', code: 'br' },
  { name: 'Bulgaria', code: 'bg' },
  { name: 'Canada', code: 'ca' },
  { name: 'China', code: 'cn' },
  { name: 'Colombia', code: 'co' },
  { name: 'Cuba', code: 'cu' },
  { name: 'Czech republic', code: 'cz' },
  { name: 'Egypt', code: 'eg' },
  { name: 'France', code: 'fr' },
  { name: 'Germany', code: 'de' },
  { name: 'Greece', code: 'gr' },
  { name: 'Hong kong', code: 'hk' },
  { name: 'Hungary', code: 'hu' },
  { name: 'India', code: 'in' },
  { name: 'Indonesia', code: 'id' },
  { name: 'Ireland', code: 'ie' },
  { name: 'Israel', code: 'il' },
  { name: 'Italy', code: 'it' },
  { name: 'Japan', code: 'jp' },
  { name: 'Latvia', code: 'lv' },
  { name: 'Lebanon', code: 'lb' },
  { name: 'Lithuania', code: 'lt' },
  { name: 'Malaysia', code: 'my' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Morocco', code: 'ma' },
  { name: 'Netherland', code: 'nl' },
  { name: 'New zealand', code: 'nz' },
  { name: 'Nigeria', code: 'ng' },
  { name: 'North korea', code: 'kp' },
  { name: 'Norway', code: 'no' },
  { name: 'Pakistan', code: 'pk' },
  { name: 'Philippines', code: 'ph' },
  { name: 'Poland', code: 'pl' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Romania', code: 'ro' },
  { name: 'Russia', code: 'ru' },
  { name: 'Saudi arabia', code: 'sa' },
  { name: 'Serbia', code: 'rs' },
  { name: 'Singapore', code: 'sg' },
  { name: 'Slovakia', code: 'sk' },
  { name: 'Slovenia', code: 'si' },
  { name: 'South africa', code: 'za' },
  { name: 'South korea', code: 'kr' },
  { name: 'Spain', code: 'es' },
  { name: 'Sweden', code: 'se' },
  { name: 'Switzerland', code: 'ch' },
  { name: 'Taiwan', code: 'tw' },
  { name: 'Thailand', code: 'th' },
  { name: 'Turkey', code: 'tr' },
  { name: 'Ukraine', code: 'ua' },
  { name: 'United arab emirates', code: 'ae' },
  { name: 'United kingdom', code: 'gb' },
  { name: 'United states of america', code: 'us' },
  { name: 'Venezuela', code: 've' },
];

export const USStatesList = [
  { image: '/state-flags/Alabama.png', name: 'Alabama', code: 'AL' },
  { image: '/state-flags/Alaska.png', name: 'Alaska', code: 'AK' },
  { image: '/state-flags/Arizona.png', name: 'Arizona', code: 'AZ' },
  { image: '/state-flags/Arkansas.png', name: 'Arkansas', code: 'AR' },
  { image: '/state-flags/California.png', name: 'California', code: 'CA' },
  { image: '/state-flags/Colarado.jpg', name: 'Colorado', code: 'CO' },
  { image: '/state-flags/Connecticut.png', name: 'Connecticut', code: 'CT' },
  { image: '/state-flags/Delaware.png', name: 'Delaware', code: 'DE' },
  {
    image: '/state-flags/District-Of-Columbia.png',
    name: 'District Of Columbia',
    code: 'DC',
  },
  { image: '/state-flags/Florida.png', name: 'Florida', code: 'FL' },
  { image: '/state-flags/Georgia.png', name: 'Georgia', code: 'GA' },
  { image: '/state-flags/Hawaii.png', name: 'Hawaii', code: 'HI' },
  { image: '/state-flags/Idaho.png', name: 'Idaho', code: 'ID' },
  { image: '/state-flags/Illinois.png', name: 'Illinois', code: 'IL' },
  { image: '/state-flags/Indiana.png', name: 'Indiana', code: 'IN' },
  { image: '/state-flags/Iowa.png', name: 'Iowa', code: 'IA' },
  { image: '/state-flags/Kansas.png', name: 'Kansas', code: 'KS' },
  { image: '/state-flags/Kentucky.png', name: 'Kentucky', code: 'KY' },
  { image: '/state-flags/Louisiana.png', name: 'Louisiana', code: 'LA' },
  { image: '/state-flags/Maine.png', name: 'Maine', code: 'ME' },
  { image: '/state-flags/Maryland.png', name: 'Maryland', code: 'MD' },
  {
    image: '/state-flags/Massachusetts.png',
    name: 'Massachusetts',
    code: 'MA',
  },
  { image: '/state-flags/Michigan.png', name: 'Michigan', code: 'MI' },
  { image: '/state-flags/Minnesota.png', name: 'Minnesota', code: 'MN' },
  { image: '/state-flags/Mississippi.png', name: 'Mississippi', code: 'MS' },
  { image: '/state-flags/Missouri.png', name: 'Missouri', code: 'MO' },
  { image: '/state-flags/Montana.png', name: 'Montana', code: 'MT' },
  { image: '/state-flags/Nebraska.png', name: 'Nebraska', code: 'NE' },
  { image: '/state-flags/Nevada.png', name: 'Nevada', code: 'NV' },
  {
    image: '/state-flags/New-Hampshire.png',
    name: 'New Hampshire',
    code: 'NH',
  },
  { image: '/state-flags/New-Jersey.png', name: 'New Jersey', code: 'NJ' },
  { image: '/state-flags/New-Mexico.png', name: 'New Mexico', code: 'NM' },
  { image: '/state-flags/New-York.png', name: 'New York', code: 'NY' },
  {
    image: '/state-flags/North-Carolina.png',
    name: 'North Carolina',
    code: 'NC',
  },
  { image: '/state-flags/North-Dakota.png', name: 'North Dakota', code: 'ND' },
  { image: '/state-flags/Ohio.png', name: 'Ohio', code: 'OH' },
  { image: '/state-flags/Oklahoma.png', name: 'Oklahoma', code: 'OK' },
  { image: '/state-flags/Oregon.png', name: 'Oregon', code: 'OR' },
  { image: '/state-flags/Pennsylvania.png', name: 'Pennsylvania', code: 'PA' },
  { image: '/state-flags/Rhode-Island.png', name: 'Rhode Island', code: 'RI' },
  {
    image: '/state-flags/South-Carolina.png',
    name: 'South Carolina',
    code: 'SC',
  },
  { image: '/state-flags/South-Dakota.png', name: 'South Dakota', code: 'SD' },
  { image: '/state-flags/Tennessee.png', name: 'Tennessee', code: 'TN' },
  { image: '/state-flags/Texas.png', name: 'Texas', code: 'TX' },
  { image: '/state-flags/Utah.png', name: 'Utah', code: 'UT' },
  { image: '/state-flags/Vermont.png', name: 'Vermont', code: 'VT' },
  { image: '/state-flags/Virginia.png', name: 'Virginia', code: 'VA' },
  { image: '/state-flags/Washington.png', name: 'Washington', code: 'WA' },
  {
    image: '/state-flags/West-Virginia.png',
    name: 'West Virginia',
    code: 'WV',
  },
  { image: '/state-flags/Wisconsin.png', name: 'Wisconsin', code: 'WI' },
  { image: '/state-flags/Wyoming.png', name: 'Wyoming', code: 'WY' },
];

export const CountryCodes = [
  ...CountriesList.map(({ code }) => code),
  ...CountriesList.map(({ code }) => code.toUpperCase()),
];

export const CountryNames = CountriesList.map(({ name }) => name);

export const USStateCodes = USStatesList.map(({ code }) => code);

export const USStateNames = USStatesList.map(({ name }) => name);

export const USStateFlagsList = USStatesList.map((v) => ({
  iimage: `/state-flags/${v.name.toString().split(' ').join('-')}.png`,
  name: v.name,
  code: v.code,
}));
